name: CI

on:
  pull_request:

jobs:
  game-server-build:
    name: Game Server Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build game-server Docker image
      run: docker build . -f ./game_server.Dockerfile
  website-build:
    name: Website Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build website Docker image
      run: docker build . -f ./website.Dockerfile
